### ISSUE TITLE
Advanced Denoise "Report error" with Blender 2.8x and 2.9x and doesn't works

### ISSUE THREAD

**Issue by GLuke67** [MohamadZeina/blender_instant_denoise#7]
with example "Classroom"
Report Error in Blender 2.82
Traceback (most recent call last):
  File "C:\Users\LUCA\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\blender_instant_denoise.py", line 242, in execute
    self.initialise_settings()
  File "C:\Users\LUCA\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\blender_instant_denoise.py", line 218, in initialise_settings
    self.context.scene.view_layers["View Layer"].use_pass_emit = True
KeyError: 'bpy_prop_collection[key]: key "View Layer" not found'

location: <unknown location>:-1

**Comment by GLuke67** [comment]
and 2.91:

bpy.ops.object.instantadvanceddenoise()
Python: Traceback (most recent call last):
  File "C:\Users\LUCA\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\blender_instant_denoise.py", line 242, in execute
    self.initialise_settings()
  File "C:\Users\LUCA\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\blender_instant_denoise.py", line 218, in initialise_settings
    self.context.scene.view_layers["View Layer"].use_pass_emit = True
KeyError: 'bpy_prop_collection[key]: key "View Layer" not found'

location: <unknown location>:-1
